info.foo=bar 
internal.secret-key=super-secret-key-123

# MongoDB URI kết nối đến MongoDB container
spring.data.mongodb.uri=mongodb://localhost:27017/intern_training
spring.data.mongodb.auto-index-creation=true