# Cấu hình server
server.port=8081
spring.application.name=auth-service

# Cấu hình JWT
jwt.secret=my_super_secret_key_which_is_long_enough_123456789
jwt.access.expiration=3600000
jwt.refresh.expiration=86400000