# Cấu hình server
server.port=8081
spring.application.name=auth-service

# MongoDB URI kết nối đến MongoDB container
spring.data.mongodb.uri=mongodb://localhost:27017/intern_training

# Cấu hình JWT
jwt.secret=my_super_secret_key
jwt.expiration=3600000