server.port=8084
spring.application.name=cart-service

#Cấu hình mongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/intern_training_cart
spring.data.mongodb.database=intern_training_cart
spring.data.mongodb.auto-index-creation=true

spring.cloud.aws.region.static=ap-southeast-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

spring.cloud.aws.sqs.endpoint=http://localhost:4566

events.queues.add-cart-event=add-cart-event