server.port=8084
spring.application.name=cart-service

#Cấu hình mongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/intern_training_cart
spring.data.mongodb.database=intern_training_cart
spring.data.mongodb.auto-index-creation=true

# Tắt kiểm tra SSL (dùng với LocalStack)
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# Quan trọng: tắt xác thực region với LocalStack
spring.cloud.aws.region.static=ap-southeast-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# Tắt auto-startup listener nếu chưa cần consume
spring.cloud.aws.sqs.listener.auto-startup=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html