server.port=8082
spring.application.name=user-service

cloudinary.cloud-name=da2nhhcom
cloudinary.api-key=938981959839916
cloudinary.api-secret=o6JDytKipn7HfRffeL7EY5sK1mY

#Cấu hình mongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/intern_training_user
spring.data.mongodb.auto-index-creation=true